version: '3'
services:
  node:
    container_name: jubas_app
    image: node:18
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8081:8081
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - ANDROID_HOME=/Android
      - PATH=$PATH:$ANDROID_HOME/platform-tools
      - PATH=$PATH:$ANDROID_HOME/tools
      - PATH=$PATH:$ANDROID_HOME/tools/bin
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y openjdk-17-jdk        
        wget -P ~ https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip ~/commandlinetools-linux-9477386_latest.zip -d /Android
        rf -rf ~/commandlinetools-linux-9477386_latest.zip
        yes | /Android/cmdline-tools/bin/sdkmanager --sdk_root=/Android --install "platform-tools" "build-tools;33.0.0"
        npm install
        npm start